/*
 *
 * Home constants
 *
 */

export const DEFAULT_ACTION = 'app/Home/DEFAULT_ACTION';

export const LOAD_CONTROLLERS = 'app/Home/LOAD_CONTROLLERS';
export const LOAD_CONTROLLERS_ERROR = 'app/Home/LOAD_CONTROLLERS_ERROR';
export const LOAD_CONTROLLERS_SUCCESS = 'app/Home/LOAD_CONTROLLERS_SUCCESS';

export const TOGGLE_CONTROLLER = 'app/Home/TOGGLE_CONTROLLER';
export const TOGGLE_CONTROLLER_ERROR = 'app/Home/TOGGLE_CONTROLLER_ERROR';
export const TOGGLE_CONTROLLER_SUCCESS = 'app/Home/TOGGLE_CONTROLLER_SUCCESS';

export const TOGGLE_CONTROLLER_STATUS = 'app/Home/TOGGLE_CONTROLLER_STATUS';
export const TOGGLE_CONTROLLER_STATUS_ERROR = 'app/Home/TOGGLE_CONTROLLER_STATUS_ERROR';
export const TOGGLE_CONTROLLER_STATUS_SUCCESS = 'app/Home/TOGGLE_CONTROLLER_STATUS_SUCCESS';

export const SETUP_CLICK = 'app/Home/SETUP_CLICK';
